### ISSUE TITLE
Using a derived style defined in App.xaml makes UI fail to render in WASM debug

### ISSUE THREAD

**Issue by peternary** [nventive/Uno#854] opened 2019-05-10 15:20 UTC
## I'm submitting a...

- Bug report (I searched for similar issues and did not find one)

## Current behavior

If you define a style in App.xaml using the BasedOn attribute then using that style on a control causes the WASM build to fail to render, but only in Debug mode.  Release works as expected.

## Expected behavior

Derived styles should not cause issues in either Release or Debug modes

## Minimal reproduction of the problem with instructions
In Mainpage.xaml using the style BaseTextBox or building in Release mode will load properly.  Using Debug mode and the DerivedTextBox style will make render fail.
[DerivedStylesSample.zip](https://github.com/nventive/Uno/files/3167079/DerivedStylesSample.zip)

## Environment

```
Nuget Package:
Uno.UI
Package Version(s):
1.45.0-dev.1455
Affected platform(s):
- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [x] 2019 (version: 16.0.3)
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by jeromelaban** [comment] 2019-05-29 16:55
This is a duplicate of #47. For now, you'll need to move the resources in a merged dictionary referenced from `App.xaml`

**Comment by carldebilly** [comment] 2019-06-18 14:04
The reason why it's not working in `DEBUG`, it's because it's generating an exception on DEBUG and it's becoming silent in RELASE...

https://github.com/nventive/Uno/blob/d9d01e7a06f289d1188807573d3ce5487db0a35d/src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs#L2870

@jeromelaban: I think we should reopen this one, what do you think?

**Closed** 2019-06-21 15:40 UTC
Labels: area/wasm, kind/bug, priority/backlog
