### ISSUE TITLE
Static resources declared in App.xaml are not applied

### ISSUE THREAD

**Issue by zbigniew-gajewski** [nventive/Uno#47] opened 2018-06-16 17:58 UTC
**Steps to reproduce:**

1. Clone [this repository](https://github.com/zbigniew-gajewski/uno-wasm-aspnet-core), restore nuget packages, rebuild. 
2. Run **UnoTest.Web** project (right click, start new instance) - clicking the button **will increase** the counter - OK.
3. Change **MainPage.xaml** by adding **DataContext** attribute to the header:
```
<Page x:Class="UnoTest.MainPage"
      xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
      xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
      xmlns:local="using:UnoTest"
      xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
      xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
      mc:Ignorable="d"
      DataContext="{Binding MainPageViewModelInstance, Source={StaticResource Locator}}">
    
        <Grid  Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
...
</Page>
```

![image](https://user-images.githubusercontent.com/32226444/41501098-0dd15ed2-719e-11e8-806d-7bf13f8e7fd8.png)

4. In **MainPage.xaml.cs** remove (or comment) line creating a new instance of the  **MainPageViewModel** class:

```
public sealed partial class MainPage : Page
{
        public MainPage()
        {
            InitializeComponent();
//            DataContext = new MainPageViewModel();
        }
  } 
```
![image](https://user-images.githubusercontent.com/32226444/41501130-93a41450-719e-11e8-9371-d3e2ee6fddde.png)

5. Rebuild the whole solution. 

**Result**:
6. Run **UnoTest.UWP** project (right click, start new instance) - clicking the button **will increase** the counter - **correct behavior** after change.
7. Run **UnoTest.Web** project (right click, start new instance) - clicking the button **will not increase** the counter - **bad behavior** after change.

**Expected result**:
After running **UnoTest.Web** app, clicking the button should increase the counter.

**Comment by jeromelaban** [comment] 2018-06-16 18:54
This is a known issue for WASM, this works for iOS and Android. 

The best workaround for now is to [declare it in a merged resource dictionary](https://github.com/nventive/Uno.MvvmLight.sample-crossplatform-flowers/blob/8676b4d69845d94be885813435c1e3981c2188c4/Flowers.Shared/Styles/Styles.xaml#L9).

**Comment by carldebilly** [comment] 2019-06-19 16:56
I reproduced the problem and I found the cause... it's very far from the reported bug.

## The actual cause
The _Wasm_ version of MvvmLight will use the **netstandard1.0** version of the package and the IoC in this version won't implement the `IServiceLocator`.

See those lines: <https://github.com/nventive/uno.mvvmlight/blob/3408287579ace291c9519edefc8017df6a151aac/GalaSoft.MvvmLight/GalaSoft.MvvmLight.Extras%20(PCL)/Ioc/ISimpleIoc.cs#L38-L40>

Since the project `Uno.Core` is compiled in ***netstandard2.0*, it will include his own version of `CommonServiceLocator` (v1.3) as defined in this bug I just opened: <https://github.com/nventive/Uno.Core/issues/53>

## What is happening in the app
1. The initial navigation to `MainPage.xaml` will be initiated
2. In the `MainPage.xaml` _InitializeComponent()_, Uno will successfully resolve the `Locator` resource
3. Uno will call the `MainPageViewModelInstance` property of `ViewModelLocator`
4. This one will cast `SimpleIoc.Default as IServiceLocator`, which is not implemented this way

   Code here: <https://github.com/zbigniew-gajewski/uno-wasm-aspnet-core/blob/78e9491427166d4a4242ddbec85e7080c38f51e9/UnoTest/UnoTest.Shared/ViewModels/ViewModelLocator.cs#L24>
5. A null-reference exception will terminate the initial navigation, leading to the false interpretation there's a problem with resources.

I will close this bug as not related to Uno directly (the real issue has been created in `Uno.Core` project). Feel free to reopen it or ask more details.

**Closed by carldebilly** 2019-06-19 16:56 UTC
Labels: kind/bug

**Comment by carldebilly** [comment] 2019-06-19 17:02
Ooohhh... by the way, to find this problem I found those 2 assemblies must be removed from _linker_ in the `LinkerConfig.xml`:

``` xml
<assembly fullname="UnoTest.Wasm" />
<assembly fullname="GalaSoft.MvvmLight.Platform" />
```

**Comment by zbigniew-gajewski** [comment] 2019-06-19 17:56
1. Thanks for diagnosing the bug. 
2. Unfortunately without `<assembly fullname="UnoTest.Wasm" />` accessing data with BreezeSharp doesn't work, I mean, the list with received data is not displayed.

**Comment by carldebilly** [comment] 2019-06-19 18:19
When I said _removed from linker_, it means those lines must be added to the config file ;-)

Sorry for the confusion.

**Comment by zbigniew-gajewski** [comment] 2019-06-19 18:27
Aaa, OK :) Thanks.
