### ISSUE TITLE
MouseWheel is interpreted as click by Slider

### ISSUE THREAD

**Issue by dr1rrb** [nventive/Uno#530] opened 2019-01-28 15:48 UTC
## I'm submitting a...
- Bug report (I searched for similar issues and did not find one)

## Current behavior
If I use the wheel of my mouse while over a `Slider`, the cursor moves directly under my mouse. 

## Expected behavior
Like on UWP, when I scroll over a slider, the mouse event should not be handled. So for instance it can be handled by a parent `ScrollViewer`.

## Minimal reproduction of the problem with instructions
- Go to: XAML Samples / Transforms / Basics
- Put your mouse over a `Slider` and scroll

## Environment
Nuget Package: Uno.UI

Package Version(s): 1.43.0-dev.687

Affected platform(s):
- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio: _irrelevant_
- [x] 2017 (version: )
- [ ] 2017 Preview (version: )
- [ ] for Mac (version: )

Relevant plugins: _none_

**Comment by MartinZikmund** [comment] 2019-02-12 17:59
This is actually not a bug. You can verify by launching any other app within the Android emulator that if there is no ScrollViewer under the pointer, you will actually get a "pointer down" input when you scroll with your mouse. 

This behavior can be turned off in the Android Emulator settings on the **Settings** tab as seen in the following image:

![Disable mouse wheel](https://user-images.githubusercontent.com/1075116/52657140-44a5e280-2ef8-11e9-91dd-48fa03a4c794.png)

**Comment by ghuntley** [comment] 2019-05-27 19:34
# UWP behaviour

![67EEE11C-7BF6-4DAD-AF4B-4B22BD206369](https://user-images.githubusercontent.com/127353/58436440-afc2a000-8108-11e9-8566-213114b2f93f.GIF)

# Android behaviour

When using the emulator defaults

![53CC19DE-C8ED-4397-97A1-32A84A1F6548](https://user-images.githubusercontent.com/127353/58436530-37101380-8109-11e9-8f69-45d1d03d84dd.GIF)

# Observations

- When `disable mousewheel` is off this behaviour reproduces
- When `disable mousewheel` is on this behaviour stops.

Thoughts - @MartinZikmund was right on the money. Thanks Martin. Closing this out.

**Closed by ghuntley** 2019-05-27 19:34 UTC
Labels: area/android, kind/bug, priority/backlog, triage/unresolved

**Comment by jeromelaban** [comment] 2019-05-27 19:37
Can we detect that setting ? Maybe we could work around it.

**Comment by MartinZikmund** [comment] 2019-05-27 19:49
Good question. Not sure if the emulator settings are surfaced somehow to the app
