### ISSUE TITLE
WASM Assertion at /mnt/jenkins/workspace/ with <MonoRuntimeDebuggerEnabled Condition="'$(Configuration)'=='Debug'">true</MonoRuntimeDebuggerEnabled>

### ISSUE THREAD

**Issue by iosub** [nventive/Uno#614] opened 2019-02-20 16:55 UTC
## I'm submitting a...

Bug report (I searched for similar issues and did not find one) 
 

## Current behavior
if I set 
MonoRuntimeDebuggerEnabled Condition="'$(Configuration)'=='Debug'">true</MonoRuntimeDebuggerEnabled
on the wasm.csproj

I get 
mono.js:1 * Assertion at /mnt/jenkins/workspace/test-mono-mainline-wasm/label/ubuntu-1804-amd64/mono/mini/interp/transform.c:2860, condition `<disabled>' not met

(anonymous) @ mono.js:1
call_method @ mono.js:1
(anonymous) @ mono.js:1
dispatchEvent @ Uno.UI.js:1293
eventHandler @ Uno.UI.js:757
mono.js:1 Uncaught abort(). Build with -s ASSERTIONS=1 for more info.

## Expected behavior
this is new to Uno.UI Version="1.43.0-dev.897" 
with version Version="1.43.0-dev.809" I dont get the error

## Minimal reproduction of the problem with instructions

update to  Uno.UI Version="1.43.0-dev.897" and set 
MonoRuntimeDebuggerEnabled Condition="'$(Configuration)'=='Debug'">true</MonoRuntimeDebuggerEnabled
on the wasm.csproj

## Environment

```
Nuget Package: 
"Uno.UI" Version="1.43.0-dev.897"
"Uno.Wasm.Bootstrap" Version="1.0.0-dev.196" 

Package Version(s): 

Affected platform(s):
- [ ] iOS
- [ ] Android
- [ X] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ X] 2017 (version: 15.9.7 )
- [ ] 2017 Preview (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )
```

**Comment by jeromelaban** [comment] 2019-02-20 17:48
This is a mono issue, will be resolved once https://github.com/mono/mono/issues/12981 is fixed.

**Comment by iosub** [comment] 2019-02-20 18:09
well Im getting all mono issues :-)
I'm waiting for this issue also, Can you also report it to mono ? https://github.com/nventive/Uno/issues/540

**Comment by iosub** [comment] 2019-03-06 18:04
hi

is there a workaround for this bug? 

thanks

**Comment by jeromelaban** [comment] 2019-03-06 18:06
It looks like this was either fixed or worked around in the latest mono-wasm. I'll make a boostrapper update that uses the latest bits.

**Comment by jeromelaban** [comment] 2019-03-06 18:14
You can follow https://github.com/nventive/Uno.Wasm.Bootstrap/pull/63

**Comment by iosub** [comment] 2019-03-06 19:51
hi 
I have update to version
Uno.ui to 950
Uno.Wasm:bootstrap 200
and I get the same error

I have try with Uno.UI 1.43.0-dev.beta-update-no-animation-transforms.813
and I dont get the error

Steps to reproduce
1.- Create a New Uno App Project
2.- Update Nuget pacages
3.- Add to wasm project   MonoRuntimeDebuggerEnabled Condition="'$(Configuration)'=='Debug'">true</MonoRuntimeDebuggerEnabled

**Comment by jeromelaban** [comment] 2019-03-06 19:55
Then it may not be fixed in the latest mono... https://github.com/mono/mono/issues/12981 will still need to be fixed by the mono team.

**Comment by jeromelaban** [comment] 2019-03-15 02:41
I've found the cause of the issue, I'll make a workaround in Uno so it does not happen anymore (at least not for this location).

**Closed** 2019-03-15 12:29 UTC
Labels: wasm
